name: geofence_tracker
description: "Geofence Tracker"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  http: ^1.1.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_local_notifications: ^19.1.0
  geofence_service: ^6.0.0+1
  geolocator_android: 4.6.1
  geolocator: ^13.0.4
  permission_handler: ^12.0.0+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true